/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BridginessPanel.java
 *
 * Created on Feb 2, 2014, 7:32:36 PM
 */

package org.ixxi.bridginess;

/**
 *
 * @author matteo
 */
public class BridginessPanel extends javax.swing.JPanel {

    /** Creates new form BridginessPanel */
    public BridginessPanel() {
        initComponents();
    }
    
    public int getExclNeighbors() {
        return jSliderExclNeighbors.getValue();
    }

    void setExclNeighbors(int exclNeighbors) {
        jSliderExclNeighbors.setValue(exclNeighbors);
    }
    
    public int getMinPathLength() {
        return jSliderPathLength.getValue();
    }

    void setMinPathLength(int minPathLength) {
        jSliderPathLength.setValue(minPathLength);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderPathLength = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSliderExclNeighbors = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jSliderPathLength.setMajorTickSpacing(1);
        jSliderPathLength.setMaximum(5);
        jSliderPathLength.setMinimum(3);
        jSliderPathLength.setPaintLabels(true);
        jSliderPathLength.setPaintTicks(true);
        jSliderPathLength.setSnapToTicks(true);
        jSliderPathLength.setValue(3);
        jSliderPathLength.setName(""); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel1.toolTipText")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel2.text")); // NOI18N

        jSliderExclNeighbors.setMajorTickSpacing(1);
        jSliderExclNeighbors.setMaximum(1);
        jSliderExclNeighbors.setMinimum(1);
        jSliderExclNeighbors.setPaintLabels(true);
        jSliderExclNeighbors.setPaintTicks(true);
        jSliderExclNeighbors.setSnapToTicks(true);
        jSliderExclNeighbors.setToolTipText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jSliderExclNeighbors.toolTipText")); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel3.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderPathLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSliderExclNeighbors, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jSliderPathLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderExclNeighbors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel3)
                    .addContainerGap(272, Short.MAX_VALUE)))
        );

        jSliderPathLength.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jSliderPathLength.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSliderExclNeighbors;
    private javax.swing.JSlider jSliderPathLength;
    // End of variables declaration//GEN-END:variables

}
