/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BridginessPanel.java
 *
 * Created on Feb 2, 2014, 7:32:36 PM
 */

package org.ixxi.bridginess;

/**
 *
 * @author matteo
 */
public class BridginessPanel extends javax.swing.JPanel {

    /** Creates new form BridginessPanel */
    public BridginessPanel() {
        initComponents();
    }
    
    public int getExclNeighbors() {
        return jSliderExclNeighbors.getValue();
    }

    void setExclNeighbors(int exclNeighbors) {
        jSliderExclNeighbors.setValue(exclNeighbors);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderExclNeighbors = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jSliderExclNeighbors.setMajorTickSpacing(1);
        jSliderExclNeighbors.setMaximum(6);
        jSliderExclNeighbors.setMinimum(3);
        jSliderExclNeighbors.setPaintLabels(true);
        jSliderExclNeighbors.setPaintTicks(true);
        jSliderExclNeighbors.setSnapToTicks(true);
        jSliderExclNeighbors.setName(""); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel1.toolTipText")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(BridginessPanel.class, "BridginessPanel.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderExclNeighbors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderExclNeighbors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider jSliderExclNeighbors;
    // End of variables declaration//GEN-END:variables

}
